name: Build y despliegue de test
on:
  push:
    branches: [ "master" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: matiuh/argo-app-test:${{ github.sha }}

  k8s-manifest-update:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
    - name: Clone app repo
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'matiuhart'
        repository: 'argo-k8s-configs'
        access-token: ${{ secrets.API_TOKEN_GITHUB }}

    - name:  Update k8s manifest
      run: |
          echo ${{ github.sha }}
          cat ./argo-k8s-configs/manifests/app-test/deployment.yaml | grep "image:"
          sed -i "s|image:.*|image: matiuh/argo-app-test:${{ github.sha }}|g" ./argo-k8s-configs/manifests/app-test/deployment.yaml
          cat ./argo-k8s-configs/manifests/app-test/deployment.yaml | grep "image:"

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'argo-k8s-configs'
        destination-github-username: 'matiuhart'
        destination-repository-name: 'argo-k8s-configs'
        user-email: matias@mtu-it.com.ar
        target-branch: master
